### PR TITLE
Operation base and simple functions on top of it

### PR DESCRIPTION
**Pull request by justpresident**
Hi, George!
It seems that first part of work is complete. Your basic functions work absolutely stable and fast. User don't need to think about any timeouts at all.
The base for basic operations created to implement all other logic, allowing to avoid code duplication.
I believe we can write much more minimal and fast lib than provided by itead.

Any feedback is much appreciated!

### CODE REVIEW

**Comment by justpresident** [comment]
I am working on server logic right now. And already added confServer and ReceiveMessage functions.
And now, with all that code base it was so simple and required minimum of thinking!
Yes, there is some chaos in method and variable names style. What style do you think is better? Like itead provided, under_case, CamelCase or javaStyle?

**Comment by giannoug** [comment]
Hello Roman,

Thanks for the commits! Unfortunately I don't have the time to work on the
project. Do you want me to make you an administrator on my repo or do you
want to continue working on your own repo?

Thanks,
George

**Comment by justpresident** [comment]
Are you serious, George? It would be great to be admin for this project!
There are some people who are already starred and watching it.

2015-01-20 22:11 GMT+03:00 George <notifications@github.com>:

**Comment by giannoug** [comment]
Great timing, I am currently doing some research on the ESP8266

This is what I am studying right now:
https://github.com/sleemanj/ESP8266_Simple/

On Sat, Jan 24, 2015 at 12:21 AM, Roman Studenikin <notifications@github.com

**Pull request merged**
